FROM python:3.10-slim

WORKDIR /shop_web

COPY . /shop_web

RUN apt-get update && \
    apt-get install -y libgl1 libzbar0 && \
    pip install --no-cache-dir flask pillow numpy opencv-python pyzbar gunicorn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["gunicorn", "-b", "0.0.0.0:8080", "shop_app:app"]